### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by frapell** [collective/collective.portlet.twitter#5]
Hey @hvelarde or @avelino Could you guys make a new release of this package? so it would include this fix https://github.com/collective/collective.portlet.twitter/commit/5e47a2b7a8ece2643c5605613021ebea7acc597b

Thank you!

**Comment by hvelarde** [comment]
do you mind to open a PR with your change so we can make a code review and merge it after tests have passed? please revert the commit on master branch after that.

**Comment by frapell** [comment]
@hvelarde The problem is documented here http://ale-rt.github.io/posts/how-to-port-plone4-portlets-to-plone5.html and my change is exactly that, adding one line with the needed "schema" property. I don't think we need this bureaucracy for such a simple change?

Plus, Travis-CI config is broken https://travis-ci.org/collective/collective.portlet.twitter and it is completely unrelated to this.

**Comment by hvelarde** [comment]
yes, I see and you're right; the problem is tests were passing before your commit and now are broken:

https://travis-ci.org/collective/collective.portlet.twitter/branches

I know is not your fault but somebody has to fix them.

**Comment by frapell** [comment]
Ok, thank you!
